### ISSUE TITLE
Can't seem to get it to work

### ISSUE THREAD

**Issue by adamwilborn** [fmjensen/Stream-Deck-Tarkov-Time#1] opened 2022-07-14 13:33 UTC
Hey there! So I've been trying to use your plugin ever since you released v2 but I haven't been able to get it to work. I download the file like I do for other plugins, accept the popup to install it, and then add it to my stream deck. When I'm in a raid I hit the button but the only thing that happens is the yellow triangle with the exclamation point pops up. Would really love to use this extension, could you help me debug what I'm doing wrong?

**Comment by fmjensen** [comment] 2022-07-14 13:39
I recomend you use the [latest release](https://github.com/fmjensen/Stream-Deck-Tarkov-Time/releases/latest) - there was some bugs in the previous versions that might cause what you describe. I hope this helps otherwise please let me know.

Thank you for the feedback!

**Comment by adamwilborn** [comment] 2022-07-14 14:18
I just tried that release again in a scav run and it didn't work. Wonder if it's somehow tied to your computer and it's a path thing? I can give you my discord or another form of contact if you want to help walk through this issue.

**Comment by fmjensen** [comment] 2022-07-14 15:22
I will do what i can to help - including discord communication but I noticed you write that you *tried the plugin in a scav run*?
What precisely do you mean about that?
The plugin should work independantly all the time no matter if EFT is running or not.

**Comment by adamwilborn** [comment] 2022-07-14 15:25
I was under the impression that it only worked in raids but I see now that's not the case. But yeah it doesn't work for me when I'm in Tarkov and not in Tarkov. Here is my discord if you want to reach out to me on there: AWilborn#0571

**Comment by fmjensen** [comment] 2022-07-15 05:37
Can you look in `%appdata%\Elgato\StreamDeck\Plugins\com.cmdrflemming.tarkovtime.sdPlugin\log` and tell me if you find log-files in that folder? 
I sendt you a Discord request a few seconds ago.

**Comment by fmjensen** [comment] 2022-07-15 08:29
The logfile will be named `sampleplugin.log` because i did not change that filename to reflect the relation to com.cmdrflemming.tarkovtime - it will be fixed in next release.

**Comment by fmjensen** [comment] 2022-07-15 19:50
After some investigation together with @adamwilborn we figured out that my plugin require **.NET Core 3.1**

After installing the **.NET Desktop Runtime 3.1.27** from here https://dotnet.microsoft.com/en-us/download/dotnet/3.1 the plugin immediately started to work as intended.

**Closed as completed by fmjensen** 2022-07-15 19:50 UTC
